USE [master]
GO

/****** Object:  Database [RailWaySystem]    Script Date: 18.03.2025 22:30:48 ******/
CREATE DATABASE [RailWaySystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RailWaySystem', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\RailWaySystem.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RailWaySystem_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\RailWaySystem_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RailWaySystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RailWaySystem] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RailWaySystem] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RailWaySystem] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RailWaySystem] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RailWaySystem] SET ARITHABORT OFF 
GO

ALTER DATABASE [RailWaySystem] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RailWaySystem] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RailWaySystem] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RailWaySystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RailWaySystem] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RailWaySystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RailWaySystem] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RailWaySystem] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RailWaySystem] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RailWaySystem] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RailWaySystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RailWaySystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RailWaySystem] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RailWaySystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RailWaySystem] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RailWaySystem] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RailWaySystem] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RailWaySystem] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [RailWaySystem] SET  MULTI_USER 
GO

ALTER DATABASE [RailWaySystem] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RailWaySystem] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RailWaySystem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RailWaySystem] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [RailWaySystem] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [RailWaySystem] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [RailWaySystem] SET QUERY_STORE = OFF
GO

ALTER DATABASE [RailWaySystem] SET  READ_WRITE 
GO

